export const projectsData = [
  {
    id: 1,
    title: "Mr. Lucass",
    description: "The website of a real estate developer.",
    image: "/images/mrLucass.webp",
    github: "https://github.com/alexvieru1/MrLucass",
    deploy: "https://mr-lucass.com",
    contributors: [],
    technologies: [
      "/images/technologies/nextjs.svg",
      "/images/technologies/typescript.svg",
      "/images/technologies/tailwind-css.svg",
      "/images/technologies/react.webp",
      "/images/technologies/node-js.svg",
    ],
    details:
      "Introducing my latest project: a bespoke presentation website crafted for real estate developer Mr. Lucass, based in Constanta, Romania. This comprehensive platform showcases Lucass's premier properties, construction stages, strategic location insights, and detailed about and contact sections. From elegant apartment layouts to dynamic construction updates, this website encapsulates Lucass's commitment to excellence in the realm of modern urban living, offering a seamless digital experience for potential clients.",
    createdAt: "15th of January 2024",
  },
  {
    id: 2,
    title: "Pizza Express",
    description: "A website for a fictional pizza joint.",
    image: "/images/pizzaExpress.webp",
    github: "https://github.com/alexvieru1/PizzaOrderWebsite",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/express-js.svg",
      "/images/technologies/html.webp",
      "/images/technologies/css.svg",
      "/images/technologies/bootstrap.svg",
    ],
    details:
      "Presenting our collaborative triumph: a dynamic pizza ordering website developed by our talented team. With a user-friendly interface, enticing menu options, and seamless shopping cart functionality, our platform redefines the pizza ordering experience. From customizable toppings to swift checkout processes, every aspect of this website is meticulously designed to delight pizza enthusiasts and streamline the ordering process. Join us on a journey of culinary convenience and satisfaction as we revolutionize the way people enjoy their favorite slices, one click at a time.",
    createdAt: "19th of April 2023",
  },
  {
    id: 3,
    title: "Homes & Condos Rental",
    description: "A web-based rental service based on AirBnB's API.",
    image: "/images/airbNb.webp",
    github: "https://github.com/alexvieru1/HomesAndCondoRentals",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/express-js.svg",
      "/images/technologies/react.webp",
      "/images/technologies/mongo-db.webp",
      "/images/technologies/mui.webp",
      "/images/technologies/api.webp",
    ],
    details:
      "Introducing our collaborative triumph: a cutting-edge website for home and condo rentals, leveraging Airbnb's API to offer seamless bookings, authentic reviews, and personalized user accounts. Harnessing the power of Airbnb's expansive database, our platform provides users with unparalleled access to a diverse range of rental options, coupled with intuitive booking processes and secure transactions. With robust review functionalities integrated seamlessly, guests can make informed decisions, while hosts can showcase their properties with confidence. Join us as we redefine the rental landscape, merging innovation with the trusted infrastructure of Airbnb to deliver an unparalleled experience in the world of home sharing.",
    createdAt: "19th of May 2023",
  },
  {
    id: 6,
    title: "Crystal HR Advisor",
    description: "Transportation HR website.",
    image: "/images/crystalHrAdvisor.webp",
    github: "https://github.com/suntruxi/crystal-hrAdvisor",
    deploy: "https://crystalhradvisor.com",
    contributors: ["Ruxandra Cristescu"],
    technologies: [
      "/images/technologies/nextjs.svg",
      "/images/technologies/typescript.svg",
      "/images/technologies/tailwind-css.svg",
      "/images/technologies/framer.webp",
    ],
    details:
      "Crystal HR Advisor is a specialized HR consultancy firm dedicated solely to the transportation industry. With deep expertise in HR and a keen understanding of the sector's specific needs and challenges, they aim to connect transportation companies with the talent they need to accelerate growth and optimize operations. Offering access to an extensive talent network, efficient and cost-effective processes, precise identification of HR needs, streamlined recruitment procedures, and a 30-day guarantee for each hire, they ensure a seamless experience for employers seeking top talent in transportation.",
    createdAt: "25th of March 2024",
  },
  {
    id: 4,
    title: "Pokemon Duel",
    description: "A battle game, based on Pokemon's official API.",
    image: "/images/pokemon.webp",
    github: "https://github.com/Rzvone/PokemonDuel",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/express-js.svg",
      "/images/technologies/react.webp",
      "/images/technologies/api.webp",
    ],
    details:
      "Behold our team's imaginative creation: a thrilling website inspired by the Pokémon universe, where players embark on a real-world adventure to capture Pokémon through strategic duels. Leveraging the power of Pokémon's API, our platform seamlessly integrates location-based gameplay, challenging players to travel to various locations and engage in thrilling battles with wild Pokémon. With each victorious duel, players have the exhilarating opportunity to capture their defeated opponent, adding them to their collection. Join us on this epic journey as we blend the virtual realm with reality, bringing the magic of Pokémon to life in an innovative and immersive gaming experience.",
    createdAt: "4th of May 2023",
  },
  {
    id: 5,
    title: "Color Up",
    description: "Nails & Lashes saloon with e-commerce of products.",
    image: "/images/colorUp.webp",
    github: "https://github.com/Rzvone/colorup",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/java.svg",
      "/images/technologies/spring-boot.svg",
      "/images/technologies/javascript.svg",
      "/images/technologies/react.webp",
      "/images/technologies/api.webp",
      "/images/technologies/mui.webp",
      "/images/technologies/mongo-db.webp",
      "/images/technologies/postgres.svg",
    ],
    details:
      "Step into the world of beauty and elegance with our team's latest achievement – a bespoke website for a nails and lashes salon, complete with user login functionality, appointment scheduling, and a seamless e-commerce platform for beauty products. This all-inclusive digital space invites users to personalize their salon experience through secure logins, ensuring a tailored and convenient journey. With a user-friendly appointment system, clients can effortlessly schedule their beauty sessions, while our integrated e-commerce section allows them to explore and purchase high-quality beauty products from the comfort of their homes. Join us in redefining the beauty industry's online presence, where sophistication meets convenience, and every click brings you closer to a pampering experience like no other.",
    createdAt: "18th of August 2023",
  },
  {
    id: 7,
    title: "Funeral Services",
    description: "Funeral services website.",
    image: "/images/funeralServices.webp",
    github: "https://github.com/CleanCodeRo/serviciiFunerarePresentation",
    contributors: ["Razvan Bobonea"],
    technologies: [
      "/images/technologies/nextjs.svg",
      "/images/technologies/typescript.svg",
      "/images/technologies/tailwind-css.svg",
      "/images/technologies/framer.webp",
    ],
    details:
      "Introducing our solemn yet dignified creation: a presentation website dedicated to funeral services, crafted with reverence and compassion. Our platform serves as a digital sanctuary, offering solace and support to those navigating the challenging process of arranging funeral ceremonies and commemorating the lives of loved ones. With a thoughtful and minimalist design, we provide essential information about our services, including burial and cremation options, memorial arrangements, and grief support resources. Through heartfelt testimonials and a discreet contact portal, we aim to provide comfort and guidance during this sensitive time. Join us as we honor the legacy of those we've lost, offering a beacon of hope and remembrance in their memory.",
    createdAt: "20th of February 2024",
  },
];
