export const projectsData = [
  {
    id: 1,
    title: "Mr. Lucass",
    description: "The website of a real estate developer.",
    image: "/images/mrLucass.webp",
    github: "https://github.com/alexvieru1/MrLucass",
    contributors: [],
    technologies: [
      "/images/technologies/nextjs.svg",
      "/images/technologies/typescript.svg",
      "/images/technologies/tailwind-css.svg",
      "/images/technologies/react.webp",
      "/images/technologies/node-js.svg",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
  {
    id: 2,
    title: "Pizza Express",
    description: "A website for a fictional pizza joint.",
    image: "/images/pizzaExpress.webp",
    github: "https://github.com/alexvieru1/PizzaOrderWebsite",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/html.webp",
      "/images/technologies/express-js.svg",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
  {
    id: 3,
    title: "Homes & Condos Rental",
    description: "A web-based rental service based on AirBnB's API.",
    image: "/images/airbNb.webp",
    github: "https://github.com/alexvieru1/HomesAndCondoRentals",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/express-js.svg",
      "/images/technologies/react.webp",
      "/images/technologies/mongo-db.webp",
      "/images/technologies/mui.webp",
      "/images/technologies/api.webp",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
  {
    id: 4,
    title: "Pokemon Duel",
    description: "A battle game, based on Pokemon's official API.",
    image: "/images/pokemon.webp",
    github: "https://github.com/Rzvone/PokemonDuel",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/javascript.svg",
      "/images/technologies/express-js.svg",
      "/images/technologies/react.webp",
      "/images/technologies/api.webp",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
  {
    id: 5,
    title: "Color Up",
    description: "Nails & Lashes saloon with e-commerce of products.",
    image: "/images/colorUp.webp",
    github: "https://github.com/Rzvone/colorup",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "/images/technologies/java.svg",
      "/images/technologies/javascript.svg",
      "/images/technologies/react.webp",
      "/images/technologies/mui.webp",
      "/images/technologies/mongo-db.webp",
      "/images/technologies/postgres.svg",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
  {
    id: 6,
    title: "Funeral Services",
    description: "Funeral services website.",
    image: "/images/funeralServices.webp",
    github: "https://github.com/CleanCodeRo/serviciiFunerarePresentation",
    contributors: ["Razvan Bobonea"],
    technologies: [
      "/images/technologies/nextjs.svg",
      "/images/technologies/typescript.svg",
      "/images/technologies/tailwind-css.svg",
      "/images/technologies/framer.webp",
    ],
    details:
      "Introducing a showcase of my latest website project! This portfolio piece encapsulates my dedication to crafting captivating digital experiences that resonate with audiences. From concept to execution, I poured my creativity and expertise into every pixel, ensuring that the final product not only meets but exceeds expectations. This project demonstrates my ability to blend cutting-edge design with seamless functionality, resulting in a website that is both visually stunning and user-friendly. Dive in to explore how I brought this vision to life and discover the transformative impact it can have on your digital presence.",
    createdAt: "1st of May 2023",
  },
];
