export const technologiesLogos = [
  { src: "/images/technologies/nextjs.svg", alt: "Next.js" },
  { src: "/images/technologies/typescript.svg", alt: "TypeScript" },
  { src: "/images/technologies/java.svg", alt: "Java" },
  { src: "/images/technologies/spring-boot.svg", alt: "Spring Boot" },
  { src: "/images/technologies/docker.svg", alt: "Docker" },
  { src: "/images/technologies/javascript.svg", alt: "JavaScript" },
  { src: "/images/technologies/react.webp", alt: "React" },
  { src: "/images/technologies/node-js.svg", alt: "Node.js" },
  { src: "/images/technologies/express-js.svg", alt: "Express.js" },
  { src: "/images/technologies/api.webp", alt: "API" },
  { src: "/images/technologies/mongo-db.webp", alt: "MongoDB" },
  { src: "/images/technologies/postgres.svg", alt: "PostgreSQL" },
  { src: "/images/technologies/html.webp", alt: "HTML" },
  { src: "/images/technologies/css.svg", alt: "CSS" },
  { src: "/images/technologies/framer.webp", alt: "Framer" },
  { src: "/images/technologies/tailwind-css.svg", alt: "Tailwind CSS" },
  { src: "/images/technologies/bootstrap.svg", alt: "Bootstrap" },
  { src: "/images/technologies/mui.webp", alt: "Material-UI" },
];
